[feat] 회원가입(join) 기능 페이지
ESC-CoM/esc-client pull request #15
Opened 2022-03-06 10:42 UTC by juyeong-s

## 💡 이슈
resolve #2

## 🤩 개요
회원가입 기능 구현 pr입니다.

## 🧑‍💻 작업 사항
- 기본정보 입력 페이지
  - 이메일
  - 비밀번호
  - 비밀번호 확인
  - 휴대폰 인증
    - 인증번호 입력
  - 성별
  - 생년월일
- 약관동의
  - 이용약관 동의
  - 개인정보 수집 및 이용 동의

## 📖 참고 사항
공유할 내용, 레퍼런스, 추가로 발생할 것으로 예상되는 이슈, 스크린샷 등을 넣어 주세요.

- 회원가입 약관 동의인 `ToS`는 `Terms of service`입니다.
- 약관내용은 추후 넣어야할 것 같습니다.
- `ToS 컴포넌트`는 기본정보(BasicInfo) 하단에 같이 추가할 예정입니다.
- 아래 코드와 같이, **생년월일**에 보여줄 임시 데이터를 배열에 저장하여 보여주도록 구현했는데 더 좋은 방법이 있다면 코멘트 달아주시면 감사하겠습니다.
`const monthList = Array.from({ length: 12 }, (_, index) => 1 + index + '월');`

![화면 기록 2022-03-06 오후 7 39 44](https://user-images.githubusercontent.com/63364990/156919658-7068f9eb-6509-41e0-ab5d-8ecfe96d5993.gif)

2022-03-07 04:34 UTC, kingyong9169 requested changes
수고하셨습니다! 항상 컴포넌트와 파일명을 일치해주세요! html 요소에 필요한 type, aria-label, htmlFor, 시맨틱 태그 등 웹접근성 고려를 해주시길 바랍니다. 또한, 변수명을 직관적으로 바꿔주시면 감사하겠습니다. pr올리실 때 조금 더 작은 단위로 올려주시면 감사하겠습니다. 그리고 커밋 단위가 너무 작은 것들이 있어 이 부분도 고려해주시면 감사하겠습니다.

2022-03-07 04:34 UTC, kingyong9169 commented on src/components/Join/BasicJoin/index.tsx
> +              <option value={''}>---</option>
중괄호 빼주세요~

2022-03-07 04:34 UTC, kingyong9169 commented on src/components/Join/BasicJoin/style.module.scss
> +      margin: 8% auto;
마진을 %로 주신게 반응형 때문인가요?

2022-03-07 04:34 UTC, kingyong9169 commented on src/styles/_color.scss
> +$primary-transparent: #ff5c6750;
얘는 왜 숫자가 8자리인가요?

2022-03-07 04:34 UTC, kingyong9169 commented on src/components/Join/BasicJoin/style.module.scss
> +}
반응형 좋네요  나중에 재사용할 수도 있으니 `_mixin.scss`에 넣어주시면 감사하겠습니다!

2022-03-07 04:34 UTC, kingyong9169 commented on src/components/Join/BasicJoin/yup.tsx
> +    .max(30, '비밀번호는 영문, 숫자 포함 최대 30자입니다.')
이 부분은 백엔드와 나중에 협의해서 최소, 최대 문자 개수를 정하는게 좋을 것 같습니다~

2022-03-07 04:34 UTC, kingyong9169 commented on src/components/Join/BasicJoin/index.tsx
> +export default function BasicInfo() {
컴포넌트는 BasicInfo인데 파일명은 BasicJoin이네요. `BasicInfo`로 맞춰주세요!

2022-03-07 04:34 UTC, kingyong9169 commented on src/components/Join/BasicJoin/style.module.scss
> +}
반응형으로 만들어주신 부분 좋네요. 다만 재사용할 수도 있으니 `_mixin.scss`에 넣어서 사용해주세요!

2022-03-07 04:34 UTC, kingyong9169 commented on src/components/Join/PersonalityJoin/index.tsx
> +export default function Personality() {
이 컴포넌트도 마찬가지로 `Personality`인데 파일명은 `PersonalityJoin`이네요. Personality`로 맞춰주세요!

2022-03-07 04:34 UTC, kingyong9169 commented on src/components/Join/ToS/index.tsx
> +export default function ToS() {
`ToS`보다는 `Terms`가 직관적인 것 같습니다. 파일명, 컴포넌트명 둘다 바꿔주세요!

2022-03-07 04:34 UTC, kingyong9169 commented on src/components/Join/ToS/index.tsx
> +  c2: boolean;
`c1, c2`보다는 개인정보 동의, 약관 동의를 영어 이름으로 바꿔서 써주세요! 무슨 이름인지 직관적이지 않아요.

2022-03-07 04:34 UTC, kingyong9169 commented on src/components/Join/BasicJoin/style.module.scss
> +  appearance: none;
이 부분 같은 경우 이 컴포넌트에서만 사용하는 것이 아니고 모든 브라우저 공통적으로 사용하기 때문에 `reset.scss`에 반영해주세요.

2022-03-07 04:34 UTC, kingyong9169 commented on src/components/Join/Terms/index.tsx
> +              !watchCondition[0] ? (
`const [personalAgree, acceptAgree] = watchCondition`처럼 비구조화 할당해서 사용해주세요!

2022-03-07 04:34 UTC, kingyong9169 commented on src/components/Join/Terms/index.tsx
> +          <label>이용약관 동의</label>
라벨보다는 `strong, em`을 사용해주세요. 라벨은 주로 인풋에 씁니다.

2022-03-07 04:34 UTC, kingyong9169 commented on src/components/Join/Terms/index.tsx
> +          <div className={style.content}>
여기에는 `div`를 씌울 필요가 없지 않나요? p가 inline속성이라 `width, height`등 여러 속성을 넣지 못하는 이유라면 `display`를 `block, inline-block`속성을 주고 수정할 수 있을 것 같습니다.

2022-03-07 04:34 UTC, kingyong9169 commented on src/components/Join/Terms/index.tsx
> +          <div className={style.content}>
마찬가지로 div를 빼는 방안을 생각해주시길 바랍니다!

2022-03-07 04:34 UTC, kingyong9169 commented on src/components/Join/Terms/index.tsx
> +        <button type="submit" className={style.next_btn}>
`aria-label` 붙여주세요.

2022-03-07 04:34 UTC, kingyong9169 commented on src/components/Join/BasicJoin/index.tsx
> +          <label>
`htmlFor`넣어주세요.

2022-03-07 05:34 UTC, juyeong-s commented on src/components/Join/BasicJoin/style.module.scss
> +  appearance: none;
그 `mixin.scss` 여기에 넣는게 맞지 않을까요..?  `mixin.scss`에 넣을까 했는데 다른 분들도 `input`을 스타일링 할 때 추가 속성이 필요하다거나 좀 다르게 하실까봐 일단 join쪽에만 넣었었습니다
`mixin.scss`가 맞다면 여기서 빼서 커밋하겠습니다

2022-03-07 05:34 UTC, juyeong-s commented on src/components/Join/BasicJoin/index.tsx
> +          <label>{errors.email ? errors.email?.message : '이메일'}</label>
`input`마다 `id`값을 줘야해서 안하긴 했는데 아무래도 있는게 낫겠네여
`button은` 따로 레이블을 부여하지 말라고 되어있고, `select`도 공식문서에 기재된 게 없어서 .. 일단 `input`에만 연관짓도록 하겠습니당

2022-03-07 05:34 UTC, juyeong-s commented on src/components/Join/BasicJoin/style.module.scss
> +      margin: 8% auto;
그렇긴 한데, `px`값으로 두는게 나을까요?

2022-03-07 05:34 UTC, juyeong-s commented on src/components/Join/BasicJoin/style.module.scss
> +}
넵

2022-03-07 05:34 UTC, juyeong-s commented on src/components/Join/PersonalityJoin/index.tsx
> +export default function Personality() {
아 이 부분도 `PersonalityJoin`으로 바꿨었는데 안바뀌었네요 뒤에 `Join`을 붙일지 말지가 고민이에요 ㅋㅋㅋㅋ

2022-03-07 05:34 UTC, juyeong-s commented on src/components/Join/Terms/index.tsx
> +              !watchCondition[0] ? (
아하 넵

2022-03-07 05:34 UTC, juyeong-s commented on src/components/Join/Terms/index.tsx
> +          <div className={style.content}>
음 이 부분은 `네이버 이용약관 동의`를 참고해서 구현했는데 `div`안에 `p`태그를 넣는 식으로 구현되어 있더라고요
약관 내용이 한 문단만 쭉 있는게 아니라 내용이 여러개 들어가서 문단 별로 여러개 나눠야 하기 때문에 `div`안에 `p`를 하나씩 넣는 식으로 하는게 좋지 않을까 생각합니다!

2022-03-07 05:34 UTC, juyeong-s commented on src/components/Join/Terms/index.tsx
> +        <button type="submit" className={style.next_btn}>
오 그래서 공식문서를 찾아봤는데
```
텍스트 레이블이 화면에 표시되지 않을 때에 사용하세요. 만약에 요소에 레이블을 정의하는 화면에 보이는 텍스트가 있다면  aria-labelledby 을 대신 사용하세요
```
라고 명시되어 있는데 저희는 버튼에 `다음`이라는 텍스트가 명시 되어 있어서 `aria-labelledby`를 쓰는거 어떤가요??
다른 텍스트로 명시되어 있는 버튼들도 마찬가지로요 ! 참고하면 좋을거같아요

2022-03-07 05:34 UTC, juyeong-s commented on src/styles/_color.scss
> +$primary-transparent: #ff5c6750;
이 색상은 투명도가 들어가서 6자리로 설정되어 있습니당

2022-03-08 03:33 UTC, soonitoon approved these changes
작업 수고하셨습니다!

2022-03-08 03:33 UTC, soonitoon commented on src/components/Join/BasicJoin/index.tsx
> +  const dayList = Array.from({ length: 31 }, (_, index) => 1 + index + '일');
`Array.from()`에서 매핑을 사용할 수 있다는 걸 처음 알았습니다 ㅎㅎ

2022-03-08 06:40 UTC, juyeong-s commented on .eslintrc
> -    "array-bracket-spacing": ["error", "always", { "arraysInArrays": false }]
이 부분 충돌이 났어서 삭제했어요!

2022-03-08 06:40 UTC, juyeong-s commented on src/components/Join/BasicJoin/style.module.scss
> +@import '../../../styles/mixin';
오 감사합니다 한번 해볼게요

2022-03-08 09:57 UTC, soonitoon commented on .eslintrc
> -    "array-bracket-spacing": ["error", "always", { "arraysInArrays": false }]
아하...! 저도 배열 브라켓에 공백 넣는 부분에서 자꾸 충돌이 발생했는데, 한번 회의에서 논의해봐도 좋을 것 같아요!

2022-03-09 08:37 UTC, juyeong-s commented on .eslintrc
> -    "array-bracket-spacing": ["error", "always", { "arraysInArrays": false }]
아 이부분 제쪽에만 수정이 되어 있어서 충돌이 났었나보네요 ㅠ

2022-03-09 08:48 UTC, kingyong9169 approved these changes

2022-03-09 08:48 UTC, kingyong9169 commented on src/styles/_mixin.scss
> +  appearance: none;
이 부분 혹시 `reset.scss`에서 설정해주실 수 있나여?

2022-03-09 08:54 UTC, merged

2022-03-09 11:47 UTC, kingyong9169 commented
주영님 생각해보니까 밑에 푸터 빼야되네여..